package com.enford.market.model;

import android.os.Parcel;
import android.os.Parcelable;

public class EnfordProductDepartment implements Parcelable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_department.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_department.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_department.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_department.city_id
     *
     * @mbggenerated
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enford_product_department.comp_id
     *
     * @mbggenerated
     */
    private Integer compId;

    private String cityName;

    private String compName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_department.id
     *
     * @return the value of enford_product_department.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_department.id
     *
     * @param id the value for enford_product_department.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_department.code
     *
     * @return the value of enford_product_department.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_department.code
     *
     * @param code the value for enford_product_department.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_department.name
     *
     * @return the value of enford_product_department.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_department.name
     *
     * @param name the value for enford_product_department.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_department.city_id
     *
     * @return the value of enford_product_department.city_id
     *
     * @mbggenerated
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_department.city_id
     *
     * @param cityId the value for enford_product_department.city_id
     *
     * @mbggenerated
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enford_product_department.comp_id
     *
     * @return the value of enford_product_department.comp_id
     *
     * @mbggenerated
     */
    public Integer getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enford_product_department.comp_id
     *
     * @param compId the value for enford_product_department.comp_id
     *
     * @mbggenerated
     */
    public void setCompId(Integer compId) {
        this.compId = compId;
    }

    public String getCityName() {
        return cityName;
    }

    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    public String getCompName() {
        return compName;
    }

    public void setCompName(String compName) {
        this.compName = compName;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeString(this.code);
        dest.writeString(this.name);
        dest.writeValue(this.cityId);
        dest.writeValue(this.compId);
        dest.writeString(this.cityName);
        dest.writeString(this.compName);
    }

    public EnfordProductDepartment() {
    }

    protected EnfordProductDepartment(Parcel in) {
        this.id = (Integer) in.readValue(Integer.class.getClassLoader());
        this.code = in.readString();
        this.name = in.readString();
        this.cityId = (Integer) in.readValue(Integer.class.getClassLoader());
        this.compId = (Integer) in.readValue(Integer.class.getClassLoader());
        this.cityName = in.readString();
        this.compName = in.readString();
    }

    public static final Parcelable.Creator<EnfordProductDepartment> CREATOR = new Parcelable.Creator<EnfordProductDepartment>() {
        public EnfordProductDepartment createFromParcel(Parcel source) {
            return new EnfordProductDepartment(source);
        }

        public EnfordProductDepartment[] newArray(int size) {
            return new EnfordProductDepartment[size];
        }
    };
}